var Question=[{q:"What is the capital of China?",a:"Beijing"},
                  {q:"Who is the Prime Minister of india?",a:"Narendra modi"},
                  {q:"Who is the world biggest Animal?",a:"Blue Whale"},
                  {q:"What is the currency of South Africa?",a:"Rand"},
                  {q:"The Battle of Plassey was fought in?",a:"1757"},
                  {q:"Each year World Red Cross and Red Crescent Day is celebrated on",a:"May 8"},
                  {q:"The world smallest country is?",a:"Vatican City"},
                  {q:"The brighest planet is?",a:"Venus"},
                  {q:"The planet nearest to the Sun is?",a:" Mercury"},
                  {q:"Which is considered as the biggest port of India??",a:"Mumbai"},
                  {q:"The gas used for making vegetables is?",a:"Hydrogen"},
                  {q:" Pink city in India is?",a:"Jaipur"},
                  {q:"The state which has desert in India is?",a:"Rajasthan"},
                  {q:"What is the name of first British to visit India?",a:"Hawkins"},
                  {q:"Name of the first election commissioner of India?",a:"Sukumar sen"},
                  {q:"Name of the first university of India ?",a:"Nalanda university"},
                  {q:"Name of the first Chinese pilgrim to visit India ?",a:"Fahien"},
                  {q:"What is the chemical symbol for the element oxygen?",a:"O2"},
                  {q:"The highest mountain on earth is?",a:"Everest"},
                  {q:"Pure water has a pH level of a around?",a:"7"},
                  {q:"Is the compound ‘HCl’ an acid or base?",a:"Acid"},
                  {q:"True or false? The fastest land animal in the world is the zebra.",a:"Wrong"},
                  {q:"True or false? DNA is the shortened form of the term ‘Deoxyribonucleic acid’?",a:"True"}]

 exports.Question=Question;