var student_data=[{name:'Ananthu',state:'Kerla',vehicle:'3',capital:'Thiruvananthapuram',
population:'33.3 million',main_crop:'Rubber',mobile_oprator:'BSNL,Idea'},
{name:'Prasanjit',state:'West Bengal',vehicle:'1',capital:'Kolkata',
population:'90.32 million',main_crop:'Tea',mobile_oprator:'Tata Docomo'},
{name:'Pooja Prajapati',state:'Uttar pradesh',vehicle:'2',capital:'Lucknow',
population:'207 million',main_crop:'Sugarcane',mobile_oprator:'Airtel'},
{name:'Pooja Rani',state:'Punjab',vehicle:'4',capital:'Chandigarh',
population:'28.8 million',main_crop:'Wheat',mobile_oprator:'Airtel,Tata Docomo'},
{name:'Vishnu',state:'Delhi',vehicle:'2',capital:'New Delhi',
population:'9.879 million',main_crop:'Wheat',mobile_oprator:'MTS,Aircel'},
{name:'Gaurav',state:'Maharastra',vehicle:'3',capital:'Mumbai',
population:'114.2 million',main_crop:'Cotton',mobile_oprator:'Idea'},
{name:'Dolly',state:'Maharastra',vehicle:'3',capital:'Mumbai',
population:'114.2 million',main_crop:'Cotton',mobile_oprator:'Aircel'},
{name:'Parmatma',state:'Uttar pradesh',vehicle:'4',capital:'Lucknow',
population:'207 million',main_crop:'Sugarcane',mobile_oprator:'Aircel,Vodafone'},
{name:'Jaiprakash',state:'Uttar pradesh',vehicle:'5',capital:'Lucknow',
population:'207 million',main_crop:'Sugarcane',mobile_oprator:'Idea,Aircel'},
{name:'Vikas',state:'Uttar pradesh',vehicle:'2',capital:'Lucknow',
population:'207 million',main_crop:'Wheat',mobile_oprator:'Tata Docomo'},
{name:'Krati',state:'Uttar pradesh',vehicle:'1',capital:'Lucknow',
population:'207 million',main_crop:'Sugarcane',mobile_oprator:'BSNL'}]

exports.data = student_data;